### ISSUE TITLE
Flask server has no dependency handling

### ISSUE THREAD

**Issue by SpyTec** [packit/dashboard#201]
While setting up the server for local development (without container) I noticed that there is nothing to indicate what you need to install when it comes to dependencies or what version you need. Ideally we should be using something similar to yarn or npm to handle dependencies and lock things down, even if it is minor

I propose that we should use poetry to set this up

```py
⬢ [fedora-toolbox:37] ❯ make run-dev-flask 
FLASK_ENV=development FLASK_APP=packit_dashboard.app flask-3 run --host=0.0.0.0
Usage: flask-3 run [OPTIONS]
Try 'flask-3 run --help' for help.

Error: While importing 'packit_dashboard.app', an ImportError was raised:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/var/home/spytec/projects/dashboard/packit_dashboard/app.py", line 3, in <module>
    from packit_dashboard.api.routes import api
  File "/var/home/spytec/projects/dashboard/packit_dashboard/api/routes.py", line 2, in <module>
    from packit_dashboard.utils import return_json
  File "/var/home/spytec/projects/dashboard/packit_dashboard/utils.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by SpyTec** [comment]
Note, this is on a fresh toolbox container
