### ISSUE TITLE
Usage page crashes

### ISSUE THREAD

**Issue by nikromen** [packit/dashboard#466]
When browsing the usage page for a while, it crashes with these tracebacks:

```
TypeError - n.defaultProps is undefined
OC@https://dashboard.packit.dev/assets/charts-CojnuqO8.js:163:19349
x@https://dashboard.packit.dev/assets/usage.lazy-9z7wy0zb.js:1:1647
L@https://dashboard.packit.dev/assets/usage.lazy-9z7wy0zb.js:1:3929
qp@https://dashboard.packit.dev/assets/vendor-BUBYV39P.js:81:16998
Gw@https://dashboard.packit.dev/assets/vendor-BUBYV39P.js:83:43963
zw@https://dashboard.packit.dev/assets/vendor-BUBYV39P.js:83:39729
SA@https://dashboard.packit.dev/assets/vendor-BUBYV39P.js:83:39657
bl@https://dashboard.packit.dev/assets/vendor-BUBYV39P.js:83:39508
wh@https://dashboard.packit.dev/assets/vendor-BUBYV39P.js:83:35875
Dw@https://dashboard.packit.dev/assets/vendor-BUBYV39P.js:83:34826
b@https://dashboard.packit.dev/assets/vendor-BUBYV39P.js:68:1558
C@https://dashboard.packit.dev/assets/vendor-BUBYV39P.js:68:1919
```

```
TypeError - Cannot set properties of undefined (setting 'cursorLabelComponent')
TypeError: Cannot set properties of undefined (setting 'cursorLabelComponent')
    at OC (https://dashboard.packit.dev/assets/charts-CojnuqO8.js:163:19346)
    at x (https://dashboard.packit.dev/assets/usage.lazy-9z7wy0zb.js:1:1646)
    at L (https://dashboard.packit.dev/assets/usage.lazy-9z7wy0zb.js:1:3929)
    at qp (https://dashboard.packit.dev/assets/vendor-BUBYV39P.js:81:16998)
    at Gw (https://dashboard.packit.dev/assets/vendor-BUBYV39P.js:83:43963)
    at zw (https://dashboard.packit.dev/assets/vendor-BUBYV39P.js:83:39727)
    at SA (https://dashboard.packit.dev/assets/vendor-BUBYV39P.js:83:39655)
    at bl (https://dashboard.packit.dev/assets/vendor-BUBYV39P.js:83:39508)
    at wh (https://dashboard.packit.dev/assets/vendor-BUBYV39P.js:83:35875)
    at Dw (https://dashboard.packit.dev/assets/vendor-BUBYV39P.js:83:34826)
```

The first one is from firefox so I wondered whether this could be firefox issue so I switched to chromium and after while it crashed again with the second traceback.

**Comment by Venefilyn** [comment]
Heya! It's fixed in #462 and is deployed in the staging environment, can you check if it works there?

https://dashboard.stg.packit.dev/usage

**Comment by mfocko** [comment]
Now I'm not sure if I forgot to push it to prod, or didn't even want to do it :eyes:

**Comment by nikromen** [comment]
yep works on stg instance :clinking_glasses:
